name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup bash
      run: |
        bash --version
        
    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck
        shellcheck --version
      
    - name: Run linting
      run: make lint
      
    - name: Run all tests
      run: make test
      
    - name: Test summary
      if: always()
      run: |
        echo "CI execution completed"
        echo "✅ Linting passed"
        echo "✅ Tests passed"
        echo "Check the logs above for detailed results"